#include "me.h"

e_KeyBind bindings[] = {
	{ NULLPROC_KEY /* should be less than 0x20 */, nullproc },
	{ 0x7F, backdel },

	{ CTL | 'A', gotobol },
	{ CTL | 'B', backchar },
	{ CTL | 'D', forwdel },
	{ CTL | 'E', gotoeol },
	{ CTL | 'F', forwchar },
	{ CTL | 'G', ctrlg },
	{ CTL | 'H', backdel },
	{ CTL | 'J', newline_and_indent },
	{ CTL | 'K', killtext },
	{ CTL | 'L', redraw },
	{ CTL | 'M', newline },
	{ CTL | 'N', forwline },
	{ CTL | 'P', backline },
	{ CTL | 'Q', quote },
	{ CTL | 'R', risearch },
	{ CTL | 'S', fisearch },
	{ CTL | 'V', forwpage },
	{ CTL | 'Y', yank },
	{ CTL | 'Z', backpage },

	{ CTLX | '(', ctlxlp },
	{ CTLX | ')', ctlxrp },
	{ CTLX | ',', gotobob },
	{ CTLX | '.', gotoeob },
	{ CTLX | '1', onlywind },
	{ CTLX | '2', splitwind },
	{ CTLX | '?', show_misc_info },
	{ CTLX | 'E', ctlxe },
	{ CTLX | 'G', gotoline },
	{ CTLX | 'J', copyregion },
	{ CTLX | 'K', killregion },
	{ CTLX | 'L', lowerregion },
	{ CTLX | 'M', setmark },
	{ CTLX | 'O', nextwind },
	{ CTLX | 'P', prevwind },
	{ CTLX | 'R', qreplace },
	{ CTLX | 'U', upperregion },
	{ CTLX | 'X', nextbuffer },

	{ CTLX | CTL | 'A', toggle_exact_search },
	{ CTLX | CTL | 'C', quit },
	{ CTLX | CTL | 'D', clear_rpat },
	{ CTLX | CTL | 'F', filefind },
	{ CTLX | CTL | 'Q', toggle_rdonly },
	{ CTLX | CTL | 'R', terminal_resize },
	{ CTLX | CTL | 'S', filesave },
	{ CTLX | CTL | 'W', filewrite },
	{ CTLX | CTL | 'X', swapmark },
	{ CTLX | CTL | 'Z', suspend },

	{ 0, NULL }
};
