#include "estruct.h"
#include "edef.h"
#include "efunc.h"
#include "line.h"

#if NAMED_CMD
struct name_bind names[] = {
	{ "abort-command", ctrlg },
	{ "backward-character", backchar },
	{ "begin-macro", ctlxlp },
	{ "beginning-of-file", gotobob },
	{ "beginning-of-line", gotobol },
	{ "buffer-position", showcpos },
	{ "case-region-lower", lowerregion },
	{ "case-region-upper", upperregion },
	{ "case-word-capitalize", capword },
	{ "case-word-lower", lowerword },
	{ "case-word-upper", upperword },
	{ "clear-and-redraw", redraw },
	{ "copy-region", copyregion },
	{ "delete-buffer", killbuffer },
	{ "delete-next-character", forwdel },
	{ "delete-next-word", delfword },
	{ "delete-other-windows", onlywind },
	{ "delete-prev-character", backdel },
	{ "delete-prev-word", delbword },
	{ "delete-window", delwind },
	{ "end-macro", ctlxrp },
	{ "end-of-file", gotoeob },
	{ "end-of-line", gotoeol },
	{ "exchange-point-and-mark", swapmark },
	{ "execute-macro", ctlxe },
	{ "exit-emacs", quit },
	{ "find-file", filefind },
	{ "forward-character", forwchar },
	{ "goto-line", gotoline },
	{ "i-shell", spawncli },
	{ "incremental-search", fisearch },
	{ "kill-region", killregion },
	{ "kill-to-end-of-line", killtext },
	{ "last-buffer", lastbuffer },
	{ "newline", newline },
	{ "newline-and-indent", newline_and_indent },
	{ "next-buffer", nextbuffer },
	{ "next-line", forwline },
	{ "next-page", forwpage },
	{ "next-window", nextwind },
	{ "next-word", forwword },
	{ "nop", nullproc },
	{ "open-line", openline },
	{ "prev-line", backline },
	{ "prev-page", backpage },
	{ "prev-window", prevwind },
	{ "prev-word", backword },
	{ "query-replace-string", qreplace },
	{ "quick-exit", quickexit },
	{ "quote-character", quote },
	{ "reverse-incremental-search", risearch },
	{ "save-file", filesave },
	{ "scroll-next-up", scrnextup },
	{ "scroll-next-down", scrnextdw },
	{ "select-buffer", usebuffer },
	{ "set-mark", setmark },
	{ "split-current-window", splitwind },
	{ "write-file", filewrite },
	{ "yank", yank },
	{ "", NULL },	/* the end sign */
};
#endif
